### ISSUE TITLE
Missing newline in prolog

### ISSUE THREAD

**Issue by wingechr** [fraoustin/sphinx_fontawesome#2]
Hi there. 

I love the extension, but in order for it to work properly for me, I needed to modify the `__init__.py` in line 59, adding a newline:

```python
prolog += '\n'
```

Otherwise I get the warning 

```bash
WARNING: Explicit markup ends without a blank line; unexpected unindent.
```
when enabling the extension (without even using the directives).

Cheers,
Chris

**Comment by fraoustin** [comment]
Hi Chris
Do you have a sample for reproduce the bug?
what is the version python? sphinx?

**Comment by fraoustin** [comment]
Hi Cris, a new version 0.0.3 with your proposition
Thank you for help

**Comment by wingechr** [comment]
Thanks, that was quick! I was just about to prepare an example :-)
Cheers!
